services:
  pgadmin:
    container_name: artemis-pgadmin-dev01
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@gmail.com
      PGADMIN_DEFAULT_PASSWORD: super-extra-delicious
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:${PGUSER}:${PGPASSWORD}' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    networks:
      - shared-network
