services:
 api:
    build:
      context: ./webapi
      dockerfile: Dockerfile
    container_name: artemis-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    restart: always
 seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5341:5341
      - 8081:80
